# Exploratory Data Analysis with SQL

### Downloading the dataset

The dataset is in the following url:

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

### Libraries

In [ ]:
# Create an environment with Python >=3.7 & <=3.11 for library compatibility
# conda create -n basicMachineLearning python=3.7
# conda install -n basicMachineLearning ipykernel --update-deps --force-reinstall

# Libraries required.
# pip install pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 
# scikit-learn==0.20.1 requests beautifulsoup4 ipython-sql sqlalchemy==1.3.9

### Connect to the database

Loading the SQL extension and establishing a connection with the database

In [2]:
%load_ext sql

In [3]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [4]:
%sql sqlite:///my_data1.db

In [5]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

c:\Users\Alberto\.conda\envs\basicMachineLearning\lib\site-packages\pandas\core\generic.py:2882: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

Removing blank rows from the table.

In [6]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Done.

[]

Displaying the names of the unique launch sites in the dataset.

In [12]:
%sql select distinct Launch_Site from SPACEXTBL

 * sqlite:///my_data1.db
Done.

[('CCAFS LC-40',), ('VAFB SLC-4E',), ('KSC LC-39A',), ('CCAFS SLC-40',)]

Displaying 5 records where launch sites begin with the string 'CCA'

In [17]:
%sql select Launch_Site from SPACEXTBL where Launch_Site like 'CCA%' limit 5

 * sqlite:///my_data1.db
Done.

[('CCAFS LC-40',),
 ('CCAFS LC-40',),
 ('CCAFS LC-40',),
 ('CCAFS LC-40',),
 ('CCAFS LC-40',)]

Displaying the total payload mass carried by boosters launched by NASA (CRS)

In [24]:
%sql SELECT Customer, sum(PAYLOAD_MASS__KG_) as Total_Payload_Mass from SPACEXTBL where Customer like 'NASA (CRS)'

 * sqlite:///my_data1.db
Done.

[('NASA (CRS)', 45596)]

Displaying average payload mass carried by booster version F9 v1.1

In [28]:
%sql SELECT Booster_Version, avg(PAYLOAD_MASS__KG_) as Average_Payload_Mass from SPACEXTBL where Booster_Version like 'F9 v1.1'

 * sqlite:///my_data1.db
Done.

[('F9 v1.1', 2928.4)]

Listing the date when the first succesful landing outcome in ground pad was acheived.

In [31]:
%sql SELECT min(Date), Landing_Outcome from SPACEXTBL where Landing_Outcome like 'Success%'

 * sqlite:///my_data1.db
Done.

[('2015-12-22', 'Success (ground pad)')]

Listing the names of the boosters which were successfully landed on a drone ship and had a payload mass greater than 4000 but less than 6000

In [36]:
%sql SELECT Booster_Version, Landing_Outcome, PAYLOAD_MASS__KG_ from SPACEXTBL where (Landing_Outcome like 'Success%drone%') and (PAYLOAD_MASS__KG_ between 4000 and 6000)

 * sqlite:///my_data1.db
Done.

[('F9 FT B1022', 'Success (drone ship)', 4696),
 ('F9 FT B1026', 'Success (drone ship)', 4600),
 ('F9 FT  B1021.2', 'Success (drone ship)', 5300),
 ('F9 FT  B1031.2', 'Success (drone ship)', 5200)]

Listing the total number of successful and failure mission outcomes

In [45]:
%sql SELECT COUNT(CASE WHEN Mission_Outcome like 'Success%' THEN 1 ELSE NULL END) AS Success, COUNT(CASE WHEN Mission_Outcome like 'Fail%' THEN 1 ELSE NULL END) AS Fails FROM SPACEXTBL

 * sqlite:///my_data1.db
Done.

[(100, 1)]

Listing the names of the booster_versions which carried the maximum payload mass.

In [51]:
%sql SELECT Booster_Version, PAYLOAD_MASS__KG_ from SPACEXTBL group by Booster_version having PAYLOAD_MASS__KG_ = max(PAYLOAD_MASS__KG_)

 * sqlite:///my_data1.db
Done.

[('F9 B4  B1039.2', 2647),
 ('F9 B4  B1040.2', 5384),
 ('F9 B4  B1041.2', 9600),
 ('F9 B4  B1043.2', 6460),
 ('F9 B4 B1039.1', 3310),
 ('F9 B4 B1040.1', 4990),
 ('F9 B4 B1041.1', 9600),
 ('F9 B4 B1042.1', 3500),
 ('F9 B4 B1043.1', 5000),
 ('F9 B4 B1044', 6092),
 ('F9 B4 B1045.1', 362),
 ('F9 B4 B1045.2', 2697),
 ('F9 B5  B1046.1', 3600),
 ('F9 B5 B1046.2', 5800),
 ('F9 B5 B1046.3', 4000),
 ('F9 B5 B1046.4', 12050),
 ('F9 B5 B1047.2', 5300),
 ('F9 B5 B1047.3 ', 6500),
 ('F9 B5 B1048.2', 3000),
 ('F9 B5 B1048.3', 4850),
 ('F9 B5 B1048.4', 15600),
 ('F9 B5 B1048.5', 15600),
 ('F9 B5 B1049.2', 9600),
 ('F9 B5 B1049.3', 13620),
 ('F9 B5 B1049.4', 15600),
 ('F9 B5 B1049.5', 15600),
 ('F9 B5 B1049.6', 15440),
 ('F9 B5 B1049.7 ', 15600),
 ('F9 B5 B1051.2 ', 4200),
 ('F9 B5 B1051.3', 15600),
 ('F9 B5 B1051.4', 15600),
 ('F9 B5 B1051.5', 14932),
 ('F9 B5 B1051.6', 15600),
 ('F9 B5 B1056.2 ', 2268),
 ('F9 B5 B1056.3 ', 6956),
 ('F9 B5 B1056.4', 15600),
 ('F9 B5 B1058.2 ', 5500),
 ('F9 B5 B1058.3 ', 15600),
 ('F9 B5 B1058.4 ', 2972),
 ('F9 B5 B1059.2', 1977),
 ('F9 B5 B1059.3', 15410),
 ('F9 B5 B1059.4', 3130),
 ('F9 B5 B1060.2 ', 15600),
 ('F9 B5 B1060.3', 15600),
 ('F9 B5B1047.1', 7075),
 ('F9 B5B1048.1', 9600),
 ('F9 B5B1049.1', 7060),
 ('F9 B5B1050', 2500),
 ('F9 B5B1051.1', 12055),
 ('F9 B5B1054', 4400),
 ('F9 B5B1056.1 ', 2495),
 ('F9 B5B1058.1 ', 12530),
 ('F9 B5B1059.1', 2617),
 ('F9 B5B1060.1', 4311),
 ('F9 B5B1061.1 ', 12500),
 ('F9 B5B1062.1', 4311),
 ('F9 B5B1063.1', 1192),
 ('F9 FT  B1021.2', 5300),
 ('F9 FT  B1029.2', 3669),
 ('F9 FT  B1031.2', 5200),
 ('F9 FT  B1032.2', 4230),
 ('F9 FT  B1035.2', 2205),
 ('F9 FT  B1036.2', 9600),
 ('F9 FT  B1038.2', 2150),
 ('F9 FT B1019', 2034),
 ('F9 FT B1020', 5271),
 ('F9 FT B1021.1', 3136),
 ('F9 FT B1022', 4696),
 ('F9 FT B1023.1', 3100),
 ('F9 FT B1024', 3600),
 ('F9 FT B1025.1', 2257),
 ('F9 FT B1026', 4600),
 ('F9 FT B1029.1', 9600),
 ('F9 FT B1030', 5600),
 ('F9 FT B1031.1', 2490),
 ('F9 FT B1032.1', 5300),
 ('F9 FT B1034', 6070),
 ('F9 FT B1035.1', 2708),
 ('F9 FT B1036.1', 9600),
 ('F9 FT B1037', 6761),
 ('F9 FT B1038.1', 475),
 ('F9 v1.0  B0003', 0),
 ('F9 v1.0  B0004', 0),
 ('F9 v1.0  B0005', 525),
 ('F9 v1.0  B0006', 500),
 ('F9 v1.0  B0007', 677),
 ('F9 v1.1', 4535),
 ('F9 v1.1  B1003', 500),
 ('F9 v1.1 B1010', 2216),
 ('F9 v1.1 B1011', 4428),
 ('F9 v1.1 B1012', 2395),
 ('F9 v1.1 B1013', 570),
 ('F9 v1.1 B1014', 4159),
 ('F9 v1.1 B1015', 1898),
 ('F9 v1.1 B1016', 4707),
 ('F9 v1.1 B1017', 553),
 ('F9 v1.1 B1018', 1952)]

Listing records for month names, failure landing_outcomes in drone ship ,booster versions, launch_site in 2015.

**Note: SQLLite does not support monthnames. Using substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [61]:
%sql select substr(Date, 6,2) as Month, substr(Date,0,5) as Year, Landing_Outcome, Booster_Version, Launch_Site from SPACEXTBL where Landing_Outcome like 'Fail%drone%' and substr(Date,0,5)='2015'

 * sqlite:///my_data1.db
Done.

[('01', '2015', 'Failure (drone ship)', 'F9 v1.1 B1012', 'CCAFS LC-40'),
 ('04', '2015', 'Failure (drone ship)', 'F9 v1.1 B1015', 'CCAFS LC-40')]

Ranking the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [64]:
%sql SELECT Landing_Outcome, COUNT(*) AS Landing_Count FROM SPACEXTBL WHERE Date BETWEEN '2010-06-04' AND '2017-03-20' GROUP BY Landing_Outcome ORDER BY Landing_Count DESC;

 * sqlite:///my_data1.db
Done.

[('No attempt', 10),
 ('Success (drone ship)', 5),
 ('Failure (drone ship)', 5),
 ('Success (ground pad)', 3),
 ('Controlled (ocean)', 3),
 ('Uncontrolled (ocean)', 2),
 ('Failure (parachute)', 2),
 ('Precluded (drone ship)', 1)]